import { fetchRunEventStream } from './runs'
import type { GenerationLogSummary, GenerationLog, SuggestionDirection, Clarification } from './types'

/** Optional clarify-before-generate answers carried into a (re)generation request. */
export interface ClarifyOpts {
  clarifications?: Clarification[]
  clarifyRound?: number
}

export interface GenerationRequestOpts extends ClarifyOpts {
  /** Idempotency key generated by useRunStream/consumeRun caller. */
  clientRequestId?: string
  /** UI surface identity; does not enter the model prompt. */
  scopeId?: string
  branchId?: string
  /** Explicit POV override. Undefined follows the branch-local picker. */
  povCharacterId?: string
}

const POV_STORAGE_PREFIX = 'errata:pov-character'

function povStorageKey(storyId: string, branchId: string): string {
  return `${POV_STORAGE_PREFIX}:${storyId}:${branchId}`
}

/** Branch-local POV selection; undefined means Narrator or unresolved branch. */
export function readPovCharacterId(storyId: string, branchId?: string): string | undefined {
  if (typeof window === 'undefined' || !branchId) return undefined
  try {
    return localStorage.getItem(povStorageKey(storyId, branchId)) || undefined
  } catch {
    return undefined
  }
}

/** Persist one timeline's POV without leaking it into sibling timelines. */
export function writePovCharacterId(
  storyId: string,
  branchId: string | undefined,
  characterId: string | undefined,
): void {
  if (typeof window === 'undefined' || !branchId) return
  try {
    const key = povStorageKey(storyId, branchId)
    if (characterId) localStorage.setItem(key, characterId)
    else localStorage.removeItem(key)
  } catch {
    // Browser storage is recovery/convenience only.
  }
}

export function clarifyBody(opts?: ClarifyOpts): Record<string, unknown> {
  const clarifications = opts?.clarifications ?? []
  const round = opts?.clarifyRound ?? 0
  // Send the round even with no clarifications so "write anyway" (a high
  // force-proceed round) actually withholds the ask tool server-side. Without
  // this, skipping on the first round would just re-ask.
  if (!clarifications.length && round <= 0) return {}
  return { clarifications, clarifyRound: round }
}

function generationRequestBody(
  storyId: string,
  opts?: GenerationRequestOpts,
): Record<string, unknown> {
  const povCharacterId = opts?.povCharacterId ?? readPovCharacterId(storyId, opts?.branchId)
  return {
    ...clarifyBody(opts),
    ...(opts?.clientRequestId ? { clientRequestId: opts.clientRequestId } : {}),
    ...(opts?.scopeId ? { scopeId: opts.scopeId } : {}),
    ...(opts?.branchId ? { branchId: opts.branchId } : {}),
    ...(povCharacterId ? { povCharacterId } : {}),
  }
}

export const generation = {
  /** Stream prose generation as a sequenced server-owned run. */
  stream: (storyId: string, input: string, signal?: AbortSignal, opts?: GenerationRequestOpts) =>
    fetchRunEventStream(`/stories/${storyId}/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      ...(signal ? { signal } : {}),
      body: JSON.stringify({ input, saveResult: false, ...generationRequestBody(storyId, opts) }),
    }),
  /** Generate and save as a new prose fragment. */
  generateAndSave: (storyId: string, input: string, signal?: AbortSignal, opts?: GenerationRequestOpts) =>
    fetchRunEventStream(`/stories/${storyId}/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      ...(signal ? { signal } : {}),
      body: JSON.stringify({ input, saveResult: true, ...generationRequestBody(storyId, opts) }),
    }),
  /** Regenerate an existing fragment with a new prompt. */
  regenerate: (storyId: string, fragmentId: string, input: string, signal?: AbortSignal, opts?: GenerationRequestOpts) =>
    fetchRunEventStream(`/stories/${storyId}/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      ...(signal ? { signal } : {}),
      body: JSON.stringify({
        input,
        saveResult: true,
        mode: 'regenerate',
        fragmentId,
        ...generationRequestBody(storyId, opts),
      }),
    }),
  /** Refine an existing fragment with instructions. */
  refine: (storyId: string, fragmentId: string, input: string, signal?: AbortSignal, opts?: GenerationRequestOpts) =>
    fetchRunEventStream(`/stories/${storyId}/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      ...(signal ? { signal } : {}),
      body: JSON.stringify({
        input,
        saveResult: true,
        mode: 'refine',
        fragmentId,
        ...generationRequestBody(storyId, opts),
      }),
    }),
  /** Get AI-generated story direction proposals */
  proposeDirections: (storyId: string, count?: number) =>
    apiFetch<{ suggestions: SuggestionDirection[] }>(
      `/stories/${storyId}/propose-directions`,
      { method: 'POST', body: JSON.stringify({ count }) },
    ),
  /** List generation log summaries (newest first) */
  listLogs: (storyId: string) =>
    apiFetch<GenerationLogSummary[]>(`/stories/${storyId}/generation-logs`),
  /** Get a full generation log by ID */
  getLog: (storyId: string, logId: string) =>
    apiFetch<GenerationLog>(`/stories/${storyId}/generation-logs/${logId}`),
}

// Import apiFetch for the non-streaming methods
import { apiFetch } from './client'
